rym3002/rym:
  - source: jd_fruit.js
    dest: src/jd/fruit/index.js 
  - source: jd_plantBean.js
    dest: src/jd/plantBean/index.js
    
whearwee/scf:
  - source: schedule_for_scf.yaml
    dest: .github/workflows/schedule.yaml
